#!/usr/bin/env bash
set -euo pipefail

# ====== Step 3: Generate Dockerfile from Template ======
# - Nếu x-dockauto.build.dockerfile_template có giá trị -> luôn dùng template đó
# - Nếu không:
#     + Nếu Dockerfile tồn tại -> giữ nguyên
#     + Nếu không có -> generate template theo language
# - Template có comment version:
#     # dockauto-template-version: <N>
#   Version này sẽ được Step 4 dùng để tính CONFIG_HASH

dockauto_template_version_for_lang() {
  local lang="$1"
  case "$lang" in
    node)   echo "1" ;;
    python) echo "1" ;;
    java)   echo "1" ;;
    *)      echo "0" ;;
  esac
}

dockauto_render_dockerfile_template() {
  local lang="$1"
  local language_version="${2:-}"
  local template_version="$3"

  case "$lang" in
    node)
      cat <<EOF
# dockauto-template-version: ${template_version}
# Generated by dockauto for Node.js
FROM node:${language_version:-22}

WORKDIR /usr/src/app

# Install dependencies first (layer cache)
COPY package*.json ./
RUN npm install

# Copy source
COPY . .

# Default command (can be overridden in compose)
CMD ["npm", "run", "start"]
EOF
      ;;
    python)
      cat <<EOF
# dockauto-template-version: ${template_version}
# Generated by dockauto for Python
FROM python:${language_version:-3.12}-slim

WORKDIR /usr/src/app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt || true

# Copy source
COPY . .

# Default command
CMD ["python", "app.py"]
EOF
      ;;
    java)
      cat <<EOF
# dockauto-template-version: ${template_version}
# Generated by dockauto for Java (JAR)
FROM eclipse-temurin:${language_version:-21}-jre

WORKDIR /app

# Copy built artifact (you may change this)
COPY target/*.jar app.jar

# Default command
CMD ["java", "-jar", "app.jar"]
EOF
      ;;
    *)
      log_error "No built-in Dockerfile template for language '${lang}'. Please create a Dockerfile manually."
      return 1
      ;;
  esac
}

dockauto_ensure_dockerfile() {
  local project_root="${DOCKAUTO_PROJECT_ROOT:-$(pwd)}"
  local ctx="${DOCKAUTO_CFG_MAIN_BUILD_CONTEXT:-.}"
  [[ -z "$ctx" ]] && ctx="."
  local dockerfile_rel="${DOCKAUTO_CFG_MAIN_DOCKERFILE:-Dockerfile}"
  local dockerfile_template="${DOCKAUTO_CFG_DOCKERFILE_TEMPLATE:-}"
  local lang="${DOCKAUTO_CFG_LANGUAGE:-}"
  local lang_version="${DOCKAUTO_CFG_LANGUAGE_VERSION:-}"

  local dockerfile_path="${project_root}/${ctx%/}/${dockerfile_rel}"
  mkdir -p "$(dirname "$dockerfile_path")"

  local use_template_key=""
  local force_template=0

  if [[ -n "$dockerfile_template" ]]; then
    # Force use template
    use_template_key="$dockerfile_template"
    force_template=1
  else
    # Default: use language
    use_template_key="$lang"
    force_template=0
  fi

  if [[ "$force_template" -eq 0 && -f "$dockerfile_path" ]]; then
    log_info "Existing Dockerfile found at ${dockerfile_path}; not generating from template."
    return 0
  fi

  if [[ -f "$dockerfile_path" && "$force_template" -eq 1 ]]; then
    log_info "Overwriting existing Dockerfile at ${dockerfile_path} with template '${use_template_key}'."
  else
    log_info "Generating Dockerfile at ${dockerfile_path} from template '${use_template_key}'."
  fi

  local template_version
  template_version="$(dockauto_template_version_for_lang "$use_template_key")"
  if [[ "$template_version" == "0" ]]; then
    log_error "Unknown dockerfile template '${use_template_key}'."
    return 1
  fi

  # Render Dockerfile
  dockauto_render_dockerfile_template "$use_template_key" "$lang_version" "$template_version" >"$dockerfile_path"

  log_success "Dockerfile generated with dockauto-template-version=${template_version}."
}